//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVAProject.ClientApp.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LogIn", ReplyAction="http://tempuri.org/IUserService/LogInResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RVAProject.Common.CustomAppException), Action="http://tempuri.org/IUserService/LogInCustomAppExceptionFault", Name="CustomAppException", Namespace="http://schemas.datacontract.org/2004/07/RVAProject.Common")]
        string LogIn(RVAProject.Common.DTOs.UserDTO.LogInRequest logInData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LogIn", ReplyAction="http://tempuri.org/IUserService/LogInResponse")]
        System.Threading.Tasks.Task<string> LogInAsync(RVAProject.Common.DTOs.UserDTO.LogInRequest logInData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RVAProject.Common.CustomAppException), Action="http://tempuri.org/IUserService/AddUserCustomAppExceptionFault", Name="CustomAppException", Namespace="http://schemas.datacontract.org/2004/07/RVAProject.Common")]
        void AddUser(RVAProject.Common.DTOs.UserDTO.UserRequest addUserData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(RVAProject.Common.DTOs.UserDTO.UserRequest addUserData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RVAProject.Common.CustomAppException), Action="http://tempuri.org/IUserService/UpdateUserCustomAppExceptionFault", Name="CustomAppException", Namespace="http://schemas.datacontract.org/2004/07/RVAProject.Common")]
        void UpdateUser(RVAProject.Common.DTOs.UserDTO.UpdateUserRequest updateUserData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(RVAProject.Common.DTOs.UserDTO.UpdateUserRequest updateUserData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : RVAProject.ClientApp.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<RVAProject.ClientApp.UserService.IUserService>, RVAProject.ClientApp.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LogIn(RVAProject.Common.DTOs.UserDTO.LogInRequest logInData) {
            return base.Channel.LogIn(logInData);
        }
        
        public System.Threading.Tasks.Task<string> LogInAsync(RVAProject.Common.DTOs.UserDTO.LogInRequest logInData) {
            return base.Channel.LogInAsync(logInData);
        }
        
        public void AddUser(RVAProject.Common.DTOs.UserDTO.UserRequest addUserData) {
            base.Channel.AddUser(addUserData);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(RVAProject.Common.DTOs.UserDTO.UserRequest addUserData) {
            return base.Channel.AddUserAsync(addUserData);
        }
        
        public void UpdateUser(RVAProject.Common.DTOs.UserDTO.UpdateUserRequest updateUserData) {
            base.Channel.UpdateUser(updateUserData);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(RVAProject.Common.DTOs.UserDTO.UpdateUserRequest updateUserData) {
            return base.Channel.UpdateUserAsync(updateUserData);
        }
    }
}
